### ISSUE TITLE
TextGrids with a -0 xmin fail to parse

### ISSUE THREAD

**Issue by mmcauliffe** [timmahrt/praatIO#34] opened 2021-11-29 01:21 UTC
I had an MFA user run into some issues with TextGrid parsing where their TextGrids has the minimum time at "-0" for some reason, I think the source of the TextGrids was Praat itself.  Probably not too hard for PraatIO to handle this, just a matter of adding "-?" to the xmin parsing line.

**Comment by timmahrt** [comment] 2021-11-29 02:56
Sounds simple enough.  I should be able to push out a fix. I'll take a look
at it tonight?

If you have the exact textgrid, I can confirm the fix is valid for the
student's use case.

Do you know where the textgrid came from?  It might be also helpful to
alert whoever was responsible for it.

Thanks!

**Comment by timmahrt** [comment] 2021-11-29 13:50
I was able to replicate the issue.  I fixed the problem and pushed out v5.0.1 

Thanks for the bug report!

**Comment by timmahrt** [comment] 2022-01-01 12:14
I'll close this now since I think the problem is resolved.  If you are still experiencing problems, feel free to reopen. Thanks!

**Closed by timmahrt** 2022-01-01 12:14 UTC
